export const mcConstants: { [key: string]: string } = {
  'entity.minecraft.allay': 'Тихоня',
  'entity.minecraft.area_effect_cloud': 'Облако эффекта',
  'entity.minecraft.armor_stand': 'Стойка для брони',
  'entity.minecraft.arrow': 'Стрела',
  'entity.minecraft.axolotl': 'Аксолотль',
  'entity.minecraft.bat': 'Летучая мышь',
  'entity.minecraft.bee': 'Пчела',
  'entity.minecraft.blaze': 'Всполох',
  'entity.minecraft.block_display': 'Визуализатор блока',
  'entity.minecraft.boat': 'Лодка',
  'entity.minecraft.camel': 'Верблюд',
  'entity.minecraft.cat': 'Кошка',
  'entity.minecraft.cave_spider': 'Пещерный паук',
  'entity.minecraft.chest_boat': 'Грузовая лодка',
  'entity.minecraft.chest_minecart': 'Грузовая вагонетка',
  'entity.minecraft.chicken': 'Курица',
  'entity.minecraft.cod': 'Треска',
  'entity.minecraft.command_block_minecart': 'Вагонетка с командным блоком',
  'entity.minecraft.cow': 'Корова',
  'entity.minecraft.creeper': 'Крипер',
  'entity.minecraft.dolphin': 'Дельфин',
  'entity.minecraft.donkey': 'Осёл',
  'entity.minecraft.dragon_fireball': 'Файербол дракона',
  'entity.minecraft.drowned': 'Утопленник',
  'entity.minecraft.egg': 'Брошенное яйцо',
  'entity.minecraft.elder_guardian': 'Древний страж',
  'entity.minecraft.end_crystal': 'Кристалл Энда',
  'entity.minecraft.ender_dragon': 'Эндер-дракон',
  'entity.minecraft.ender_pearl': 'Брошенный эндер-жемчуг',
  'entity.minecraft.enderman': 'Эндермен',
  'entity.minecraft.endermite': 'Эндермит',
  'entity.minecraft.evoker': 'Заклинатель',
  'entity.minecraft.evoker_fangs': 'Клыки заклинателя',
  'entity.minecraft.experience_bottle': 'Брошенный пузырёк опыта',
  'entity.minecraft.experience_orb': 'Сфера опыта',
  'entity.minecraft.eye_of_ender': 'Око Эндера',
  'entity.minecraft.falling_block': 'Падающий блок',
  'entity.minecraft.falling_block_type': '%s в падении',
  'entity.minecraft.fireball': 'Файербол',
  'entity.minecraft.firework_rocket': 'Фейерверк',
  'entity.minecraft.fishing_bobber': 'Поплавок',
  'entity.minecraft.fox': 'Лисица',
  'entity.minecraft.frog': 'Лягушка',
  'entity.minecraft.furnace_minecart': 'Самоходная вагонетка',
  'entity.minecraft.ghast': 'Гаст',
  'entity.minecraft.giant': 'Гигант',
  'entity.minecraft.glow_item_frame': 'Светящаяся рамка',
  'entity.minecraft.glow_squid': 'Светящийся спрут',
  'entity.minecraft.goat': 'Коза',
  'entity.minecraft.guardian': 'Страж',
  'entity.minecraft.hoglin': 'Хоглин',
  'entity.minecraft.hopper_minecart': 'Загрузочная вагонетка',
  'entity.minecraft.horse': 'Лошадь',
  'entity.minecraft.husk': 'Кадавр',
  'entity.minecraft.illusioner': 'Иллюзор',
  'entity.minecraft.interaction': 'Взаимодействие',
  'entity.minecraft.iron_golem': 'Железный голем',
  'entity.minecraft.item': 'Предмет',
  'entity.minecraft.item_display': 'Визуализатор предмета',
  'entity.minecraft.item_frame': 'Рамка',
  'entity.minecraft.killer_bunny': 'Кролик-убийца',
  'entity.minecraft.leash_knot': 'Узел поводка',
  'entity.minecraft.lightning_bolt': 'Молния',
  'entity.minecraft.llama': 'Лама',
  'entity.minecraft.llama_spit': 'Плевок ламы',
  'entity.minecraft.magma_cube': 'Магмовый куб',
  'entity.minecraft.marker': 'Метка',
  'entity.minecraft.minecart': 'Вагонетка',
  'entity.minecraft.mooshroom': 'Муухомор',
  'entity.minecraft.mule': 'Мул',
  'entity.minecraft.ocelot': 'Оцелот',
  'entity.minecraft.painting': 'Картина',
  'entity.minecraft.panda': 'Панда',
  'entity.minecraft.parrot': 'Попугай',
  'entity.minecraft.phantom': 'Фантом',
  'entity.minecraft.pig': 'Свинья',
  'entity.minecraft.piglin': 'Пиглин',
  'entity.minecraft.piglin_brute': 'Брутальный пиглин',
  'entity.minecraft.pillager': 'Разбойник',
  'entity.minecraft.player': 'Игрок',
  'entity.minecraft.polar_bear': 'Белый медведь',
  'entity.minecraft.potion': 'Зелье',
  'entity.minecraft.pufferfish': 'Иглобрюх',
  'entity.minecraft.rabbit': 'Кролик',
  'entity.minecraft.ravager': 'Разоритель',
  'entity.minecraft.salmon': 'Лосось',
  'entity.minecraft.sheep': 'Овца',
  'entity.minecraft.shulker': 'Шалкер',
  'entity.minecraft.shulker_bullet': 'Снаряд шалкера',
  'entity.minecraft.silverfish': 'Чешуйница',
  'entity.minecraft.skeleton': 'Скелет',
  'entity.minecraft.skeleton_horse': 'Лошадь-скелет',
  'entity.minecraft.slime': 'Слизень',
  'entity.minecraft.small_fireball': 'Малый файербол',
  'entity.minecraft.sniffer': 'Нюхач',
  'entity.minecraft.snow_golem': 'Снежный голем',
  'entity.minecraft.snowball': 'Снежок',
  'entity.minecraft.spawner_minecart': 'Вагонетка с рассадником монстров',
  'entity.minecraft.spectral_arrow': 'Спектральная стрела',
  'entity.minecraft.spider': 'Паук',
  'entity.minecraft.squid': 'Спрут',
  'entity.minecraft.stray': 'Зимогор',
  'entity.minecraft.strider': 'Лавомерка',
  'entity.minecraft.tadpole': 'Головастик',
  'entity.minecraft.text_display': 'Визуализатор текста',
  'entity.minecraft.tnt': 'Активированный динамит',
  'entity.minecraft.tnt_minecart': 'Вагонетка с динамитом',
  'entity.minecraft.trader_llama': 'Лама торговца',
  'entity.minecraft.trident': 'Трезубец',
  'entity.minecraft.tropical_fish': 'Тропическая рыба',
  'entity.minecraft.tropical_fish.predefined.0': 'Амфиприон',
  'entity.minecraft.tropical_fish.predefined.1': 'Чёрная зебрасома',
  'entity.minecraft.tropical_fish.predefined.10': 'Мавританский идол',
  'entity.minecraft.tropical_fish.predefined.11': 'Разукрашенная бабочка',
  'entity.minecraft.tropical_fish.predefined.12': 'Рыба-попугай',
  'entity.minecraft.tropical_fish.predefined.13': 'Ангел-королева',
  'entity.minecraft.tropical_fish.predefined.14': 'Красная цихлида',
  'entity.minecraft.tropical_fish.predefined.15': 'Красногубая морская собачка',
  'entity.minecraft.tropical_fish.predefined.16': 'Берикс',
  'entity.minecraft.tropical_fish.predefined.17': 'Пальцепёр',
  'entity.minecraft.tropical_fish.predefined.18': 'Клоун томатный',
  'entity.minecraft.tropical_fish.predefined.19': 'Спинорог',
  'entity.minecraft.tropical_fish.predefined.2': 'Голубой хирург',
  'entity.minecraft.tropical_fish.predefined.20': 'Желтохвостая рыба-попугай',
  'entity.minecraft.tropical_fish.predefined.21': 'Зебрасома жёлтая',
  'entity.minecraft.tropical_fish.predefined.3': 'Рыба-бабочка',
  'entity.minecraft.tropical_fish.predefined.4': 'Цихлида',
  'entity.minecraft.tropical_fish.predefined.5': 'Рыба-клоун',
  'entity.minecraft.tropical_fish.predefined.6': 'Сиамский петушок',
  'entity.minecraft.tropical_fish.predefined.7': 'Грамма двухцветная',
  'entity.minecraft.tropical_fish.predefined.8': 'Трёхполосый луциан',
  'entity.minecraft.tropical_fish.predefined.9': 'Барабуля',
  'entity.minecraft.tropical_fish.type.betty': 'Петушок',
  'entity.minecraft.tropical_fish.type.blockfish': 'Блокунь',
  'entity.minecraft.tropical_fish.type.brinely': 'Красотка',
  'entity.minecraft.tropical_fish.type.clayfish': 'Глинянка',
  'entity.minecraft.tropical_fish.type.dasher': 'Живец',
  'entity.minecraft.tropical_fish.type.flopper': 'Плескун',
  'entity.minecraft.tropical_fish.type.glitter': 'Блестянка',
  'entity.minecraft.tropical_fish.type.kob': 'Горбыль',
  'entity.minecraft.tropical_fish.type.snooper': 'Сыщик',
  'entity.minecraft.tropical_fish.type.spotty': 'Пеструшка',
  'entity.minecraft.tropical_fish.type.stripey': 'Полосатка',
  'entity.minecraft.tropical_fish.type.sunstreak': 'Лучехвостка',
  'entity.minecraft.turtle': 'Черепаха',
  'entity.minecraft.vex': 'Вредина',
  'entity.minecraft.villager': 'Крестьянин',
  'entity.minecraft.villager.armorer': 'Бронник',
  'entity.minecraft.villager.butcher': 'Мясник',
  'entity.minecraft.villager.cartographer': 'Картограф',
  'entity.minecraft.villager.cleric': 'Священник',
  'entity.minecraft.villager.farmer': 'Фермер',
  'entity.minecraft.villager.fisherman': 'Рыбак',
  'entity.minecraft.villager.fletcher': 'Лучник',
  'entity.minecraft.villager.leatherworker': 'Кожевник',
  'entity.minecraft.villager.librarian': 'Библиотекарь',
  'entity.minecraft.villager.mason': 'Каменщик',
  'entity.minecraft.villager.nitwit': 'Деревенщина',
  'entity.minecraft.villager.none': 'Крестьянин',
  'entity.minecraft.villager.shepherd': 'Пастух',
  'entity.minecraft.villager.toolsmith': 'Инструментальщик',
  'entity.minecraft.villager.weaponsmith': 'Оружейник',
  'entity.minecraft.vindicator': 'Поборник',
  'entity.minecraft.wandering_trader': 'Странствующий торговец',
  'entity.minecraft.warden': 'Хранитель',
  'entity.minecraft.witch': 'Ведьма',
  'entity.minecraft.wither': 'Визер',
  'entity.minecraft.wither_skeleton': 'Визер-скелет',
  'entity.minecraft.wither_skull': 'Череп визера',
  'entity.minecraft.wolf': 'Волк',
  'entity.minecraft.zoglin': 'Зоглин',
  'entity.minecraft.zombie': 'Зомби',
  'entity.minecraft.zombie_horse': 'Лошадь-зомби',
  'entity.minecraft.zombie_villager': 'Крестьянин-зомби',
  'entity.minecraft.zombified_piglin': 'Зомбифицированный пиглин',
  'entity.not_summonable': 'Не удалось создать сущность типа %s',
  'event.minecraft.raid': 'Рейд',
  'event.minecraft.raid.defeat': 'Поражение',
  'event.minecraft.raid.raiders_remaining': 'Осталось нападающих: %s',
  'event.minecraft.raid.victory': 'Победа',
  'death.attack.anvil': '%1$s раздавлен упавшей наковальней',
  'death.attack.anvil.player':
    '%1$s был раздавлен упавшей наковальней, пока боролся с %2$s',
  'death.attack.arrow': '%1$s застрелен %2$s',
  'death.attack.arrow.item': '%1$s застрелен %2$s с помощью %3$s',
  'death.attack.badRespawnPoint.link': 'жестоких правил игры',
  'death.attack.badRespawnPoint.message': '%1$s стал жертвой %2$s',
  'death.attack.cactus': '%1$s исколот до смерти',
  'death.attack.cactus.player': '%1$s наткнулся на кактус, спасаясь от %2$s',
  'death.attack.cramming': '%1$s расплющен в лепёшку',
  'death.attack.cramming.player': '%1$s расплющен %2$s',
  'death.attack.dragonBreath': '%1$s растворился в драконьем дыхании',
  'death.attack.dragonBreath.player':
    '%1$s Был зажарен в драконьем дыхании из-за %2$s',
  'death.attack.drown': '%1$s утонул',
  'death.attack.drown.player': '%1$s утонул, спасаясь от %2$s',
  'death.attack.dryout': '%1$s умер от обезвоживания',
  'death.attack.dryout.player': '%1$s умер от обезвоживания, спасаясь от %2$s',
  'death.attack.even_more_magic': '%1$s был убит неизведанной магией',
  'death.attack.explosion': '%1$s взорвался',
  'death.attack.explosion.player': '%1$s был взорван %2$s',
  'death.attack.explosion.player.item': '%1$s был взорван %2$s с помощью %3$s',
  'death.attack.fall': '%1$s разбился вдребезги',
  'death.attack.fall.player': '%1$s разбился вдребезги, спасаясь от %2$s',
  'death.attack.fallingBlock': '%1$s раздавлен упавшим блоком',
  'death.attack.fallingBlock.player':
    '%1$s был раздавлен упавшим блоком, пока боролся с %2$s',
  'death.attack.fallingStalactite': '%1$s был пронзён обрушившимся сталактитом',
  'death.attack.fallingStalactite.player':
    '%1$s был пронзён обрушившимся сталактитом, пока боролся с %2$s',
  'death.attack.fireball': '%1$s убит файерболом %2$s',
  'death.attack.fireball.item': '%1$s убит файерболом %2$s с помощью %3$s',
  'death.attack.fireworks': '%1$s с треском разлетелся',
  'death.attack.fireworks.item':
    '%1$s с треском разлетелся из-за фейерверка %2$s, выпущенного из %3$s',
  'death.attack.fireworks.player':
    '%1$s с треском разлетелся, пока боролся с %2$s',
  'death.attack.flyIntoWall':
    '%1$s преобразовал кинетическую энергию во внутреннюю',
  'death.attack.flyIntoWall.player':
    '%1$s преобразовал кинетическую энергию во внутреннюю, спасаясь от %2$s',
  'death.attack.freeze': '%1$s замёрз насмерть',
  'death.attack.freeze.player': '%1$s замёрз насмерть благодаря %2$s',
  'death.attack.generic': '%1$s умер',
  'death.attack.generic.player': '%1$s умер из-за %2$s',
  'death.attack.hotFloor': '%1$s обнаружил, что пол — это лава',
  'death.attack.hotFloor.player': '%1$s зашёл в опасную зону из-за %2$s',
  'death.attack.inFire': '%1$s умер в огне',
  'death.attack.inFire.player': '%1$s сгорел в огне, пока боролся с %2$s',
  'death.attack.inWall': '%1$s погребён заживо',
  'death.attack.inWall.player': '%1$s был погребён заживо, пока боролся с %2$s',
  'death.attack.indirectMagic': '%1$s был убит %2$s с помощью магии',
  'death.attack.indirectMagic.item': '%1$s был убит %2$s с помощью %3$s',
  'death.attack.lava': '%1$s решил поплавать в лаве',
  'death.attack.lava.player': '%1$s упал в лаву, убегая от %2$s',
  'death.attack.lightningBolt': '%1$s был поражён молнией',
  'death.attack.lightningBolt.player':
    '%1$s был поражён молнией, пока боролся с %2$s',
  'death.attack.magic': '%1$s был убит магией',
  'death.attack.magic.player': '%1$s был убит магией, спасаясь от %2$s',
  'death.attack.message_too_long':
    'Сообщение слишком длинное для доставки. Извините! Вот сокращённая версия: %s',
  'death.attack.mob': '%1$s был убит %2$s',
  'death.attack.mob.item': '%1$s был убит %2$s с помощью %3$s',
  'death.attack.onFire': '%1$s сгорел заживо',
  'death.attack.onFire.item':
    '%1$s был поджарен, пока боролся с %2$s, с помощью %3$s',
  'death.attack.onFire.player': '%1$s был сожжён дотла, пока боролся с %2$s',
  'death.attack.outOfWorld': '%1$s выпал из мира',
  'death.attack.outOfWorld.player':
    '%1$s не захотел жить в том же мире, что и %2$s',
  'death.attack.player': '%1$s был убит %2$s',
  'death.attack.player.item': '%1$s был убит %2$s с помощью %3$s',
  'death.attack.sonic_boom': '%1$s был уничтожен звуковым зарядом',
  'death.attack.sonic_boom.item':
    '%1$s был уничтожен звуковым зарядом, спасаясь от %2$s c %3$s',
  'death.attack.sonic_boom.player':
    '%1$s был уничтожен звуковым ударом, спасаясь от %2$s',
  'death.attack.stalagmite': '%1$s пронзён сталагмитом',
  'death.attack.stalagmite.player':
    '%1$s был пронзён сталагмитом, пока боролся с %2$s',
  'death.attack.starve': '%1$s умер от голода',
  'death.attack.starve.player': '%1$s умер от голода, пока боролся с %2$s',
  'death.attack.sting': '%1$s изжален до смерти',
  'death.attack.sting.item': '%1$s был изжален до смерти %2$s с помощью %3$s',
  'death.attack.sting.player': '%1$s изжален до смерти %2$s',
  'death.attack.sweetBerryBush':
    '%1$s искололся до смерти в кустах сладких ягод',
  'death.attack.sweetBerryBush.player':
    '%1$s искололся до смерти в кустах сладких ягод, спасаясь от %2$s',
  'death.attack.thorns': '%1$s был убит, пытаясь навредить %2$s',
  'death.attack.thorns.item': '%1$s был убит %3$s, пытаясь навредить %2$s',
  'death.attack.thrown': '%1$s был избит %2$s',
  'death.attack.thrown.item': '%1$s был избит %2$s с помощью %3$s',
  'death.attack.trident': '%1$s был пронзён %2$s',
  'death.attack.trident.item': '%1$s пронзён %2$s с помощью %3$s',
  'death.attack.wither': '%1$s иссушён',
  'death.attack.wither.player': '%1$s был иссушён, пока боролся с %2$s',
  'death.attack.witherSkull': '%1$s был поражён черепом из %2$s',
  'death.attack.witherSkull.item':
    '%1$s был поражён черепом из %2$s с помощью %3$s',
  'death.fell.accident.generic': '%1$s разбился насмерть',
  'death.fell.accident.ladder': '%1$s свалился с лестницы',
  'death.fell.accident.other_climbable': '%1$s сорвался',
  'death.fell.accident.scaffolding': '%1$s сорвался с подмосток',
  'death.fell.accident.twisting_vines': '%1$s сорвался с вьющейся лозы',
  'death.fell.accident.vines': '%1$s сорвался с лианы',
  'death.fell.accident.weeping_vines': '%1$s сорвался с плакучей лозы',
  'death.fell.assist': '%1$s свалился благодаря %2$s',
  'death.fell.assist.item': '%1$s был обречён на падение %2$s с помощью %3$s',
  'death.fell.finish': '%1$s упал с высоты и был добит %2$s',
  'death.fell.finish.item':
    '%1$s упал с высоты и был добит %2$s с помощью %3$s',
  'death.fell.killer': '%1$s был обречён на падение'
}
