export const mcConstants: { [key: string]: string } = {
  'entity.minecraft.allay': 'Тихоня',
  'entity.minecraft.area_effect_cloud': 'Облако эффекта',
  'entity.minecraft.armor_stand': 'Стойка для брони',
  'entity.minecraft.arrow': 'Стрела',
  'entity.minecraft.axolotl': 'Аксолотль',
  'entity.minecraft.bat': 'Летучая мышь',
  'entity.minecraft.bee': 'Пчела',
  'entity.minecraft.blaze': 'Всполох',
  'entity.minecraft.block_display': 'Визуализатор блока',
  'entity.minecraft.boat': 'Лодка',
  'entity.minecraft.camel': 'Верблюд',
  'entity.minecraft.cat': 'Кошка',
  'entity.minecraft.cave_spider': 'Пещерный паук',
  'entity.minecraft.chest_boat': 'Грузовая лодка',
  'entity.minecraft.chest_minecart': 'Грузовая вагонетка',
  'entity.minecraft.chicken': 'Курица',
  'entity.minecraft.cod': 'Треска',
  'entity.minecraft.command_block_minecart': 'Вагонетка с командным блоком',
  'entity.minecraft.cow': 'Корова',
  'entity.minecraft.creeper': 'Крипер',
  'entity.minecraft.dolphin': 'Дельфин',
  'entity.minecraft.donkey': 'Осёл',
  'entity.minecraft.dragon_fireball': 'Файербол дракона',
  'entity.minecraft.drowned': 'Утопленник',
  'entity.minecraft.egg': 'Брошенное яйцо',
  'entity.minecraft.elder_guardian': 'Древний страж',
  'entity.minecraft.end_crystal': 'Кристалл Энда',
  'entity.minecraft.ender_dragon': 'Эндер-дракон',
  'entity.minecraft.ender_pearl': 'Брошенный эндер-жемчуг',
  'entity.minecraft.enderman': 'Эндермен',
  'entity.minecraft.endermite': 'Эндермит',
  'entity.minecraft.evoker': 'Заклинатель',
  'entity.minecraft.evoker_fangs': 'Клыки заклинателя',
  'entity.minecraft.experience_bottle': 'Брошенный пузырёк опыта',
  'entity.minecraft.experience_orb': 'Сфера опыта',
  'entity.minecraft.eye_of_ender': 'Око Эндера',
  'entity.minecraft.falling_block': 'Падающий блок',
  'entity.minecraft.falling_block_type': '%s в падении',
  'entity.minecraft.fireball': 'Файербол',
  'entity.minecraft.firework_rocket': 'Фейерверк',
  'entity.minecraft.fishing_bobber': 'Поплавок',
  'entity.minecraft.fox': 'Лисица',
  'entity.minecraft.frog': 'Лягушка',
  'entity.minecraft.furnace_minecart': 'Самоходная вагонетка',
  'entity.minecraft.ghast': 'Гаст',
  'entity.minecraft.giant': 'Гигант',
  'entity.minecraft.glow_item_frame': 'Светящаяся рамка',
  'entity.minecraft.glow_squid': 'Светящийся спрут',
  'entity.minecraft.goat': 'Коза',
  'entity.minecraft.guardian': 'Страж',
  'entity.minecraft.hoglin': 'Хоглин',
  'entity.minecraft.hopper_minecart': 'Загрузочная вагонетка',
  'entity.minecraft.horse': 'Лошадь',
  'entity.minecraft.husk': 'Кадавр',
  'entity.minecraft.illusioner': 'Иллюзор',
  'entity.minecraft.interaction': 'Взаимодействие',
  'entity.minecraft.iron_golem': 'Железный голем',
  'entity.minecraft.item': 'Предмет',
  'entity.minecraft.item_display': 'Визуализатор предмета',
  'entity.minecraft.item_frame': 'Рамка',
  'entity.minecraft.killer_bunny': 'Кролик-убийца',
  'entity.minecraft.leash_knot': 'Узел поводка',
  'entity.minecraft.lightning_bolt': 'Молния',
  'entity.minecraft.llama': 'Лама',
  'entity.minecraft.llama_spit': 'Плевок ламы',
  'entity.minecraft.magma_cube': 'Магмовый куб',
  'entity.minecraft.marker': 'Метка',
  'entity.minecraft.minecart': 'Вагонетка',
  'entity.minecraft.mooshroom': 'Муухомор',
  'entity.minecraft.mule': 'Мул',
  'entity.minecraft.ocelot': 'Оцелот',
  'entity.minecraft.painting': 'Картина',
  'entity.minecraft.panda': 'Панда',
  'entity.minecraft.parrot': 'Попугай',
  'entity.minecraft.phantom': 'Фантом',
  'entity.minecraft.pig': 'Свинья',
  'entity.minecraft.piglin': 'Пиглин',
  'entity.minecraft.piglin_brute': 'Брутальный пиглин',
  'entity.minecraft.pillager': 'Разбойник',
  'entity.minecraft.player': 'Игрок',
  'entity.minecraft.polar_bear': 'Белый медведь',
  'entity.minecraft.potion': 'Зелье',
  'entity.minecraft.pufferfish': 'Иглобрюх',
  'entity.minecraft.rabbit': 'Кролик',
  'entity.minecraft.ravager': 'Разоритель',
  'entity.minecraft.salmon': 'Лосось',
  'entity.minecraft.sheep': 'Овца',
  'entity.minecraft.shulker': 'Шалкер',
  'entity.minecraft.shulker_bullet': 'Снаряд шалкера',
  'entity.minecraft.silverfish': 'Чешуйница',
  'entity.minecraft.skeleton': 'Скелет',
  'entity.minecraft.skeleton_horse': 'Лошадь-скелет',
  'entity.minecraft.slime': 'Слизень',
  'entity.minecraft.small_fireball': 'Малый файербол',
  'entity.minecraft.sniffer': 'Нюхач',
  'entity.minecraft.snow_golem': 'Снежный голем',
  'entity.minecraft.snowball': 'Снежок',
  'entity.minecraft.spawner_minecart': 'Вагонетка с рассадником монстров',
  'entity.minecraft.spectral_arrow': 'Спектральная стрела',
  'entity.minecraft.spider': 'Паук',
  'entity.minecraft.squid': 'Спрут',
  'entity.minecraft.stray': 'Зимогор',
  'entity.minecraft.strider': 'Лавомерка',
  'entity.minecraft.tadpole': 'Головастик',
  'entity.minecraft.text_display': 'Визуализатор текста',
  'entity.minecraft.tnt': 'Активированный динамит',
  'entity.minecraft.tnt_minecart': 'Вагонетка с динамитом',
  'entity.minecraft.trader_llama': 'Лама торговца',
  'entity.minecraft.trident': 'Трезубец',
  'entity.minecraft.tropical_fish': 'Тропическая рыба',
  'entity.minecraft.tropical_fish.predefined.0': 'Амфиприон',
  'entity.minecraft.tropical_fish.predefined.1': 'Чёрная зебрасома',
  'entity.minecraft.tropical_fish.predefined.10': 'Мавританский идол',
  'entity.minecraft.tropical_fish.predefined.11': 'Разукрашенная бабочка',
  'entity.minecraft.tropical_fish.predefined.12': 'Рыба-попугай',
  'entity.minecraft.tropical_fish.predefined.13': 'Ангел-королева',
  'entity.minecraft.tropical_fish.predefined.14': 'Красная цихлида',
  'entity.minecraft.tropical_fish.predefined.15': 'Красногубая морская собачка',
  'entity.minecraft.tropical_fish.predefined.16': 'Берикс',
  'entity.minecraft.tropical_fish.predefined.17': 'Пальцепёр',
  'entity.minecraft.tropical_fish.predefined.18': 'Клоун томатный',
  'entity.minecraft.tropical_fish.predefined.19': 'Спинорог',
  'entity.minecraft.tropical_fish.predefined.2': 'Голубой хирург',
  'entity.minecraft.tropical_fish.predefined.20': 'Желтохвостая рыба-попугай',
  'entity.minecraft.tropical_fish.predefined.21': 'Зебрасома жёлтая',
  'entity.minecraft.tropical_fish.predefined.3': 'Рыба-бабочка',
  'entity.minecraft.tropical_fish.predefined.4': 'Цихлида',
  'entity.minecraft.tropical_fish.predefined.5': 'Рыба-клоун',
  'entity.minecraft.tropical_fish.predefined.6': 'Сиамский петушок',
  'entity.minecraft.tropical_fish.predefined.7': 'Грамма двухцветная',
  'entity.minecraft.tropical_fish.predefined.8': 'Трёхполосый луциан',
  'entity.minecraft.tropical_fish.predefined.9': 'Барабуля',
  'entity.minecraft.tropical_fish.type.betty': 'Петушок',
  'entity.minecraft.tropical_fish.type.blockfish': 'Блокунь',
  'entity.minecraft.tropical_fish.type.brinely': 'Красотка',
  'entity.minecraft.tropical_fish.type.clayfish': 'Глинянка',
  'entity.minecraft.tropical_fish.type.dasher': 'Живец',
  'entity.minecraft.tropical_fish.type.flopper': 'Плескун',
  'entity.minecraft.tropical_fish.type.glitter': 'Блестянка',
  'entity.minecraft.tropical_fish.type.kob': 'Горбыль',
  'entity.minecraft.tropical_fish.type.snooper': 'Сыщик',
  'entity.minecraft.tropical_fish.type.spotty': 'Пеструшка',
  'entity.minecraft.tropical_fish.type.stripey': 'Полосатка',
  'entity.minecraft.tropical_fish.type.sunstreak': 'Лучехвостка',
  'entity.minecraft.turtle': 'Черепаха',
  'entity.minecraft.vex': 'Вредина',
  'entity.minecraft.villager': 'Крестьянин',
  'entity.minecraft.villager.armorer': 'Бронник',
  'entity.minecraft.villager.butcher': 'Мясник',
  'entity.minecraft.villager.cartographer': 'Картограф',
  'entity.minecraft.villager.cleric': 'Священник',
  'entity.minecraft.villager.farmer': 'Фермер',
  'entity.minecraft.villager.fisherman': 'Рыбак',
  'entity.minecraft.villager.fletcher': 'Лучник',
  'entity.minecraft.villager.leatherworker': 'Кожевник',
  'entity.minecraft.villager.librarian': 'Библиотекарь',
  'entity.minecraft.villager.mason': 'Каменщик',
  'entity.minecraft.villager.nitwit': 'Деревенщина',
  'entity.minecraft.villager.none': 'Крестьянин',
  'entity.minecraft.villager.shepherd': 'Пастух',
  'entity.minecraft.villager.toolsmith': 'Инструментальщик',
  'entity.minecraft.villager.weaponsmith': 'Оружейник',
  'entity.minecraft.vindicator': 'Поборник',
  'entity.minecraft.wandering_trader': 'Странствующий торговец',
  'entity.minecraft.warden': 'Хранитель',
  'entity.minecraft.witch': 'Ведьма',
  'entity.minecraft.wither': 'Визер',
  'entity.minecraft.wither_skeleton': 'Визер-скелет',
  'entity.minecraft.wither_skull': 'Череп визера',
  'entity.minecraft.wolf': 'Волк',
  'entity.minecraft.zoglin': 'Зоглин',
  'entity.minecraft.zombie': 'Зомби',
  'entity.minecraft.zombie_horse': 'Лошадь-зомби',
  'entity.minecraft.zombie_villager': 'Крестьянин-зомби',
  'entity.minecraft.zombified_piglin': 'Зомбифицированный пиглин',
  'entity.not_summonable': 'Не удалось создать сущность типа %s',
  'event.minecraft.raid': 'Рейд',
  'event.minecraft.raid.defeat': 'Поражение',
  'event.minecraft.raid.raiders_remaining': 'Осталось нападающих: %s',
  'event.minecraft.raid.victory': 'Победа',
  'death.attack.anvil': ' раздавлен упавшей наковальней',
  'death.attack.anvil.player':
    ' был раздавлен упавшей наковальней, пока боролся с ',
  'death.attack.arrow': ' застрелен ',
  'death.attack.arrow.item': ' застрелен с помощью ',
  'death.attack.badRespawnPoint.link': 'жестоких правил игры',
  'death.attack.badRespawnPoint.message': ' стал жертвой ',
  'death.attack.cactus': ' исколот до смерти',
  'death.attack.cactus.player': ' наткнулся на кактус, спасаясь от ',
  'death.attack.cramming': ' расплющен в лепёшку',
  'death.attack.cramming.player': ' расплющен ',
  'death.attack.dragonBreath': ' растворился в драконьем дыхании',
  'death.attack.dragonBreath.player':
    ' Был зажарен в драконьем дыхании из-за ',
  'death.attack.drown': ' утонул',
  'death.attack.drown.player': ' утонул, спасаясь от ',
  'death.attack.dryout': ' умер от обезвоживания',
  'death.attack.dryout.player': ' умер от обезвоживания, спасаясь от ',
  'death.attack.even_more_magic': ' был убит неизведанной магией',
  'death.attack.explosion': ' взорвался',
  'death.attack.explosion.player': ' был взорван ',
  'death.attack.explosion.player.item': ' был взорван  с помощью ',
  'death.attack.fall': ' разбился вдребезги',
  'death.attack.fall.player': ' разбился вдребезги, спасаясь от ',
  'death.attack.fallingBlock': ' раздавлен упавшим блоком',
  'death.attack.fallingBlock.player':
    ' был раздавлен упавшим блоком, пока боролся с ',
  'death.attack.fallingStalactite': ' был пронзён обрушившимся сталактитом',
  'death.attack.fallingStalactite.player':
    ' был пронзён обрушившимся сталактитом, пока боролся с ',
  'death.attack.fireball': ' убит файерболом ',
  'death.attack.fireball.item': ' убит файерболом  с помощью ',
  'death.attack.fireworks': ' с треском разлетелся',
  'death.attack.fireworks.item':
    ' с треском разлетелся из-за фейерверка , выпущенного из ',
  'death.attack.fireworks.player':
    ' с треском разлетелся, пока боролся с ',
  'death.attack.flyIntoWall':
    ' преобразовал кинетическую энергию во внутреннюю',
  'death.attack.flyIntoWall.player':
    ' преобразовал кинетическую энергию во внутреннюю, спасаясь от ',
  'death.attack.freeze': ' замёрз насмерть',
  'death.attack.freeze.player': ' замёрз насмерть благодаря ',
  'death.attack.generic': ' умер',
  'death.attack.generic.player': ' умер из-за ',
  'death.attack.hotFloor': ' обнаружил, что пол — это лава',
  'death.attack.hotFloor.player': ' зашёл в опасную зону из-за ',
  'death.attack.inFire': ' умер в огне',
  'death.attack.inFire.player': ' сгорел в огне, пока боролся с ',
  'death.attack.inWall': ' погребён заживо',
  'death.attack.inWall.player': ' был погребён заживо, пока боролся с ',
  'death.attack.indirectMagic': ' был убит  с помощью магии',
  'death.attack.indirectMagic.item': ' был убит  с помощью ',
  'death.attack.lava': ' решил поплавать в лаве',
  'death.attack.lava.player': ' упал в лаву, убегая от ',
  'death.attack.lightningBolt': ' был поражён молнией',
  'death.attack.lightningBolt.player':
    ' был поражён молнией, пока боролся с ',
  'death.attack.magic': ' был убит магией',
  'death.attack.magic.player': ' был убит магией, спасаясь от ',
  'death.attack.message_too_long':
    'Сообщение слишком длинное для доставки. Извините! Вот сокращённая версия: %s',
  'death.attack.mob': ' был убит ',
  'death.attack.mob.item': ' был убит  с помощью ',
  'death.attack.onFire': ' сгорел заживо',
  'death.attack.onFire.item':
    ' был поджарен, пока боролся с , с помощью ',
  'death.attack.onFire.player': ' был сожжён дотла, пока боролся с ',
  'death.attack.outOfWorld': ' выпал из мира',
  'death.attack.outOfWorld.player':
    ' не захотел жить в том же мире, что и ',
  'death.attack.player': ' был убит ',
  'death.attack.player.item': ' был убит  с помощью ',
  'death.attack.sonic_boom': ' был уничтожен звуковым зарядом',
  'death.attack.sonic_boom.item':
    ' был уничтожен звуковым зарядом, спасаясь от  c ',
  'death.attack.sonic_boom.player':
    ' был уничтожен звуковым ударом, спасаясь от ',
  'death.attack.stalagmite': ' пронзён сталагмитом',
  'death.attack.stalagmite.player':
    ' был пронзён сталагмитом, пока боролся с ',
  'death.attack.starve': ' умер от голода',
  'death.attack.starve.player': ' умер от голода, пока боролся с ',
  'death.attack.sting': ' изжален до смерти',
  'death.attack.sting.item': ' был изжален до смерти  с помощью ',
  'death.attack.sting.player': ' изжален до смерти ',
  'death.attack.sweetBerryBush':
    ' искололся до смерти в кустах сладких ягод',
  'death.attack.sweetBerryBush.player':
    ' искололся до смерти в кустах сладких ягод, спасаясь от ',
  'death.attack.thorns': ' был убит, пытаясь навредить ',
  'death.attack.thorns.item': ' был убит , пытаясь навредить ',
  'death.attack.thrown': ' был избит ',
  'death.attack.thrown.item': ' был избит  с помощью ',
  'death.attack.trident': ' был пронзён ',
  'death.attack.trident.item': ' пронзён  с помощью ',
  'death.attack.wither': ' иссушён',
  'death.attack.wither.player': ' был иссушён, пока боролся с ',
  'death.attack.witherSkull': ' был поражён черепом из ',
  'death.attack.witherSkull.item':
    ' был поражён черепом из  с помощью ',
  'death.fell.accident.generic': ' разбился насмерть',
  'death.fell.accident.ladder': ' свалился с лестницы',
  'death.fell.accident.other_climbable': ' сорвался',
  'death.fell.accident.scaffolding': ' сорвался с подмосток',
  'death.fell.accident.twisting_vines': ' сорвался с вьющейся лозы',
  'death.fell.accident.vines': ' сорвался с лианы',
  'death.fell.accident.weeping_vines': ' сорвался с плакучей лозы',
  'death.fell.assist': ' свалился благодаря ',
  'death.fell.assist.item': ' был обречён на падение  с помощью ',
  'death.fell.finish': ' упал с высоты и был добит ',
  'death.fell.finish.item':
    ' упал с высоты и был добит  с помощью ',
  'death.fell.killer': ' был обречён на падение'
}
