on:
  push:
    branches: ["main"]
jobs:
  update:
    runs-on: self-hosted
    steps:
    - run: cd ~/development/front/ &&  git reset --hard
    - run: cd ~/development/front/ &&  git pull --force origin main
    - run: cd ~/development/front/ && npm i
    - run: cd ~/development/front && npm run build
