on:
  push:
    branches: ['dev']
jobs:
  update:
    runs-on: self-hosted
    steps:
      - run: cd ~/development/front/ &&  git reset --hard
      - run: cd ~/development/front/ &&  git pull --force origin dev
      - run: cd ~/development/front/ && npm i
      - run: cd ~/development/front && npm run build:dev
